version: "3.8"

services:
  stankey-bot:
    build: .
    ports:
      - "8080:8080"

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'stankey'
      MYSQL_USER: 'hans_vestberg'
      MYSQL_PASSWORD: 'welovejohnstankey'
      MYSQL_ROOT_PASSWORD: 'welovejohnstankey'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - database:/var/lib/mysql

volumes:
  database:

    